pipeline {
  agent any

  environment {
    AWS_REGION   = "eu-central-1"
    CLUSTER_NAME = "lesson-7-eks"
    ECR_REGISTRY = "369751621151.dkr.ecr.eu-central-1.amazonaws.com"
    ECR_REPO     = "lesson-7-ecr"
    IMAGE_TAG    = "${BUILD_NUMBER}"
    NAMESPACE    = "default"
    RELEASE_NAME = "django-app"
    CHART_PATH   = "charts/django-app"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Build image') {
      steps {
        sh '''
          set -eux
          docker build -t ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG} -f Django/Dockerfile Django
        '''
      }
    }

    stage('Push to ECR') {
      steps {
        sh '''
          set -eux
          aws ecr get-login-password --region ${AWS_REGION} \
            | docker login --username AWS --password-stdin ${ECR_REGISTRY}
          docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}
        '''
      }
    }

    stage('Deploy to EKS (Helm)') {
      steps {
        sh '''
          set -eux
          aws eks update-kubeconfig --region ${AWS_REGION} --name ${CLUSTER_NAME}

          helm upgrade --install ${RELEASE_NAME} ${CHART_PATH} \
            -n ${NAMESPACE} \
            --set image.repository=${ECR_REGISTRY}/${ECR_REPO} \
            --set image.tag=${IMAGE_TAG}

          kubectl -n ${NAMESPACE} rollout status deployment/${RELEASE_NAME}-django --timeout=240s
          kubectl -n ${NAMESPACE} get pods -o wide
        '''
      }
    }
  }
}
